version: '3'
services:
  watchdog:
    build: .
    ports:
      - '${HOST:-127.0.0.1}:${PORT:-3000}:${PORT:-3000}'
    env_file: ./.env
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
